"""initial_schema

Revision ID: 621920b0243a
Revises: 
Create Date: 2026-09-17 10:25:16.079148
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = '621920b0243a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=160), nullable=False),
    sa.Column('starts_at', sa.DateTime(), nullable=False),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_starts_at'), 'event', ['starts_at'], unique=False)
    op.create_table('exercise',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=160), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.Column('video_filename', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('access_token', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('access_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_access_token'), 'player', ['access_token'], unique=True)
    op.create_index(op.f('ix_player_slug'), 'player', ['slug'], unique=True)
    op.create_table('standing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('team', sqlmodel.sql.sqltypes.AutoString(length=160), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('played', sa.Integer(), nullable=False),
    sa.Column('won', sa.Integer(), nullable=False),
    sa.Column('drawn', sa.Integer(), nullable=False),
    sa.Column('lost', sa.Integer(), nullable=False),
    sa.Column('goals_for', sa.Integer(), nullable=False),
    sa.Column('goals_against', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('goals_for >= 0 AND goals_against >= 0 AND points >= 0'),
    sa.CheckConstraint('played >= 0 AND won >= 0 AND drawn >= 0 AND lost >= 0'),
    sa.CheckConstraint('position >= 1'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('season', 'position'),
    sa.UniqueConstraint('season', 'team')
    )
    op.create_index(op.f('ix_standing_season'), 'standing', ['season'], unique=False)
    op.create_table('attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('attending', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'player_id')
    )
    op.create_index(op.f('ix_attendance_event_id'), 'attendance', ['event_id'], unique=False)
    op.create_index(op.f('ix_attendance_player_id'), 'attendance', ['player_id'], unique=False)
    op.create_table('convocation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('selection_status', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'player_id')
    )
    op.create_index(op.f('ix_convocation_event_id'), 'convocation', ['event_id'], unique=False)
    op.create_index(op.f('ix_convocation_player_id'), 'convocation', ['player_id'], unique=False)
    op.create_table('examperiod',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('end_date >= start_date'),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'start_date', 'end_date')
    )
    op.create_index(op.f('ix_examperiod_player_id'), 'examperiod', ['player_id'], unique=False)
    op.create_index(op.f('ix_examperiod_start_date'), 'examperiod', ['start_date'], unique=False)
    op.create_table('exerciseassignment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exercise_id', 'player_id')
    )
    op.create_index(op.f('ix_exerciseassignment_exercise_id'), 'exerciseassignment', ['exercise_id'], unique=False)
    op.create_index(op.f('ix_exerciseassignment_player_id'), 'exerciseassignment', ['player_id'], unique=False)
    op.create_table('followup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('observed_on', sa.Date(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=False),
    sa.Column('visible_to_player', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_followup_observed_on'), 'followup', ['observed_on'], unique=False)
    op.create_index(op.f('ix_followup_player_id'), 'followup', ['player_id'], unique=False)
    op.create_table('goal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=160), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('done', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('done_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goal_player_id'), 'goal', ['player_id'], unique=False)
    op.create_table('mvprecognition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('awarded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id')
    )
    op.create_index(op.f('ix_mvprecognition_event_id'), 'mvprecognition', ['event_id'], unique=False)
    op.create_index(op.f('ix_mvprecognition_player_id'), 'mvprecognition', ['player_id'], unique=False)
    op.create_table('playerstats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('season', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('games', sa.Integer(), nullable=False),
    sa.Column('goals', sa.Integer(), nullable=False),
    sa.Column('assists', sa.Integer(), nullable=False),
    sa.Column('yellow_cards', sa.Integer(), nullable=False),
    sa.Column('red_cards', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('games >= 0 AND goals >= 0 AND assists >= 0 AND yellow_cards >= 0 AND red_cards >= 0'),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'season')
    )
    op.create_index(op.f('ix_playerstats_player_id'), 'playerstats', ['player_id'], unique=False)
    op.create_index(op.f('ix_playerstats_season'), 'playerstats', ['season'], unique=False)
    op.create_table('playerstatsimport',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('season', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('source_key', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('imported_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'season', 'source_key')
    )
    op.create_index(op.f('ix_playerstatsimport_player_id'), 'playerstatsimport', ['player_id'], unique=False)
    op.create_table('reinforcement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('player_name', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('source_team', sqlmodel.sql.sqltypes.AutoString(length=160), nullable=False),
    sa.Column('playing_position', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'player_name', 'source_team')
    )
    op.create_index(op.f('ix_reinforcement_event_id'), 'reinforcement', ['event_id'], unique=False)
    op.create_table('routine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=160), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_routine_player_id'), 'routine', ['player_id'], unique=False)
    op.create_table('exerciseprogress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('iso_year', sa.Integer(), nullable=False),
    sa.Column('iso_week', sa.Integer(), nullable=False),
    sa.Column('repetitions', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('repetitions >= 0 AND repetitions <= 3'),
    sa.ForeignKeyConstraint(['assignment_id'], ['exerciseassignment.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assignment_id', 'iso_year', 'iso_week')
    )
    op.create_index(op.f('ix_exerciseprogress_assignment_id'), 'exerciseprogress', ['assignment_id'], unique=False)
    op.create_table('routineexercise',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('routine_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('target_repetitions', sa.Integer(), nullable=False),
    sa.CheckConstraint('position >= 1'),
    sa.CheckConstraint('target_repetitions >= 1'),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise.id'], ),
    sa.ForeignKeyConstraint(['routine_id'], ['routine.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('routine_id', 'exercise_id'),
    sa.UniqueConstraint('routine_id', 'position')
    )
    op.create_index(op.f('ix_routineexercise_exercise_id'), 'routineexercise', ['exercise_id'], unique=False)
    op.create_index(op.f('ix_routineexercise_routine_id'), 'routineexercise', ['routine_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_routineexercise_routine_id'), table_name='routineexercise')
    op.drop_index(op.f('ix_routineexercise_exercise_id'), table_name='routineexercise')
    op.drop_table('routineexercise')
    op.drop_index(op.f('ix_exerciseprogress_assignment_id'), table_name='exerciseprogress')
    op.drop_table('exerciseprogress')
    op.drop_index(op.f('ix_routine_player_id'), table_name='routine')
    op.drop_table('routine')
    op.drop_index(op.f('ix_reinforcement_event_id'), table_name='reinforcement')
    op.drop_table('reinforcement')
    op.drop_index(op.f('ix_playerstatsimport_player_id'), table_name='playerstatsimport')
    op.drop_table('playerstatsimport')
    op.drop_index(op.f('ix_playerstats_season'), table_name='playerstats')
    op.drop_index(op.f('ix_playerstats_player_id'), table_name='playerstats')
    op.drop_table('playerstats')
    op.drop_index(op.f('ix_mvprecognition_player_id'), table_name='mvprecognition')
    op.drop_index(op.f('ix_mvprecognition_event_id'), table_name='mvprecognition')
    op.drop_table('mvprecognition')
    op.drop_index(op.f('ix_goal_player_id'), table_name='goal')
    op.drop_table('goal')
    op.drop_index(op.f('ix_followup_player_id'), table_name='followup')
    op.drop_index(op.f('ix_followup_observed_on'), table_name='followup')
    op.drop_table('followup')
    op.drop_index(op.f('ix_exerciseassignment_player_id'), table_name='exerciseassignment')
    op.drop_index(op.f('ix_exerciseassignment_exercise_id'), table_name='exerciseassignment')
    op.drop_table('exerciseassignment')
    op.drop_index(op.f('ix_examperiod_start_date'), table_name='examperiod')
    op.drop_index(op.f('ix_examperiod_player_id'), table_name='examperiod')
    op.drop_table('examperiod')
    op.drop_index(op.f('ix_convocation_player_id'), table_name='convocation')
    op.drop_index(op.f('ix_convocation_event_id'), table_name='convocation')
    op.drop_table('convocation')
    op.drop_index(op.f('ix_attendance_player_id'), table_name='attendance')
    op.drop_index(op.f('ix_attendance_event_id'), table_name='attendance')
    op.drop_table('attendance')
    op.drop_index(op.f('ix_standing_season'), table_name='standing')
    op.drop_table('standing')
    op.drop_index(op.f('ix_player_slug'), table_name='player')
    op.drop_index(op.f('ix_player_access_token'), table_name='player')
    op.drop_table('player')
    op.drop_table('exercise')
    op.drop_index(op.f('ix_event_starts_at'), table_name='event')
    op.drop_table('event')
    # ### end Alembic commands ###
